'use strict';
const TABLE_NAME   = 'test_administration_assessment';
const TESTADMIN_ID = 'TestAdministrationID';
const ASSESSMENT_ID  = 'AssessmentID';

exports.up = function (knex, Promise) {
    return Promise.all([
        knex.schema.createTable(TABLE_NAME, function (table) {
            table.increments('TestAdministrationAssessmentID');
            table.integer(TESTADMIN_ID, 10).notNullable().unsigned();
            table.integer(ASSESSMENT_ID, 11).notNullable();
            table.timestamp('CreatedAt', true).defaultTo(knex.raw('CURRENT_TIMESTAMP'));
            table.timestamp('UpdatedAt', true).defaultTo(knex.raw('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'));
            table.foreign(TESTADMIN_ID).references(TESTADMIN_ID).inTable('test_administration');
            table.foreign(ASSESSMENT_ID).references('assessmentId').inTable('assessment');
        })
    ]).then(() => {
        // Use a custom key name, since the autogenerated key is too long
        return knex.raw('alter table `test_administration_assessment` add unique `testadmin_assessment_unique` (`' + TESTADMIN_ID + '`, `' + ASSESSMENT_ID + '`)');
    });
};

exports.down = function (knex) {
    return knex.schema.dropTable(TABLE_NAME);
};
